# Generated by Django 2.1.3 on 2018-12-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='first_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='animals',
            name='last_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
