# Generated by Django 2.1.3 on 2018-12-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181202_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
