# Generated by Django 2.1.3 on 2018-12-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
